export * from './patient/patient.model'
export * from './specialization/specialization.model'
export * from './department/department.model'
export * from './upload/upload.model'
export * from './user/user.model'
export * from './worker/worker.model'
export * from './log/log.model'
